import type { Border } from './Border';
import type { CardFace } from './CardFace';
import type { Color } from './Color';
import type { FrameEffect } from './FrameEffect';
import type { Game } from './Game';
import type { ImageUris } from './ImageUris';
import type { Layout } from './Layout';
import type { Legalities } from './Legalties';
import type { Preview } from './Preview';
import type { Prices } from './Prices';
import type { PromoType } from './PromoType';
import type { PurchaseUris } from './PurchaseUris';
import type { Rarity } from './Rarity';
import type { RelatedCard } from './RelatedCard';
import type { RelatedUris } from './RelatedUris';
import type { Set as ScryfallSet } from './Set';

export interface Card {
	// Gameplay fields
	all_parts?: RelatedCard[];
	// Core fields
	arena_id?: number;
	// Print fields
	artist?: string;
	artist_ids?: string[];
	booster: boolean;
	border_color: keyof typeof Border;
	card_back_id: string;
	card_faces?: CardFace[];
	cmc: number;
	collector_number: string;
	color_identity: Color[];
	color_indicator?: Color[];
	colors?: Color[];
	digital: boolean;
	edhrec_rank?: number;
	flavor_text?: string;
	foil: boolean;
	frame: '1993' | '1997' | '2003' | '2015' | 'Future';
	frame_effects?: (keyof typeof FrameEffect)[];
	full_art: boolean;
	games: (keyof typeof Game)[];
	hand_modifier?: string;
	highres_image: boolean;
	id: string;
	illustration_id?: string;
	image_uris?: ImageUris;
	lang: string;
	layout: keyof typeof Layout;
	legalities: Legalities;
	life_modifier?: string;
	loyalty?: string;
	mana_cost?: string;
	mtgo_foil_id?: number;
	mtgo_id?: number;
	multiverse_ids?: number[];
	name: string;
	nonfoil: boolean;
	object: 'card';
	oracle_id: string;
	oracle_text?: string;
	oversized: boolean;
	power?: string;
	preview?: Preview;
	prices: Prices;
	printed_name?: string;
	printed_text?: string;
	printed_type_line?: string;
	prints_search_uri: string;
	promo: boolean;
	promo_types?: (keyof typeof PromoType)[];
	purchase_uris: PurchaseUris;
	rarity: keyof typeof Rarity;
	related_uris: RelatedUris;
	released_at: string;
	reprint: boolean;
	reserved: boolean;
	rulings_uri: string;
	scryfall_set_uri: string;
	scryfall_uri: string;
	set: string;
	set_name: string;
	set_search_uri: string;
	set_type: ScryfallSet['set_type'];
	set_uri: string;
	story_spotlight: boolean;
	tcgplayer_id?: number;
	textless: boolean;
	toughness?: string;
	type_line: string;
	uri: string;
	variation: boolean;
	variation_of?: string;
	watermark?: string;
}
